### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by braindesigner** [braindesigner/gh-flow-practice#1]
## Tasks

- [x] Print fizz, if i is multiple of 3.
- [ ] Print buzz, if i is multiple of 5.
- [ ] Print fizzbuzz, if i is multiple of 15.
- [x] Otherwise, print i itself.
## References

- [Fizzbuzz wikipedia] (https://en.wikipedia.org/wiki/Fizz_buzz)
